version: '3.8'

services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    # Expose port for local debugging. Remove this line in production if you don't want Redis publicly reachable.
    ports:
      - "6379:6379"
    restart: unless-stopped

  requesthandler:
    build:
      context: ./requestHandler
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - redis
    restart: unless-stopped

  uploadservice:
    build:
      context: ./uploadService
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: unless-stopped

  deployservice:
    build:
      context: ./deployService
      dockerfile: Dockerfile
    env_file:
      - .env
    # worker — no public ports required
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - requesthandler
    restart: unless-stopped

volumes:
  redis-data:

# Notes:
# - Compose provides DNS-based service discovery. Inside any container, other services are reachable
#   by their service name. Example: use "redis:6379" as the host:port for Redis.
# - Put your secrets and service URLs into a top-level `.env` file (DO NOT commit secrets to git).
#   Example `.env` entries are shown in the README or below in the project docs.
